/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package MyTestProg;

import org.junit.Assert;
import org.junit.Test;

import java.util.InputMismatchException;


public class ConsoleTest {



    @Test
    public void readIntFromStdin_test_good() {

    }


    /*@Test
    public void readStringFromStdin_test() {
    }*/
}
