/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package MyTestProg;

import org.junit.Assert;
import org.junit.Test;

import java.io.ByteArrayInputStream;
import java.util.InputMismatchException;


public class ConsoleTest {

   public void provideInput(String data) {
        ByteArrayInputStream in = new ByteArrayInputStream(data.getBytes());
        System.setIn(in);
    }


    @Test
    public void test_readIntFromStdin(){
        String expectedRes = "55";
        provideInput(expectedRes);
        int res = Console.readIntFromStdin("Number:");
        Assert.assertEquals(Integer.parseInt(expectedRes), res);
    }


    /*@Test
    public void readStringFromStdin_test() {
    }*/
}
